name: Deployment Pipeline

on:
  push:
    branches:
      - main
      - dev


jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        env:
          SONAR_TOKEN: b2cca84e532a929cf7d3cf36754ecd842ba05caa
        run: |
          ./gradlew build sonar --info
          ./gradlew build jacocoTestReport sonar --info